version: '3'
services:
  marklogic:
    build: 
      context: 'marklogic'
    image: 'marklogic9:latest'
    ports:
      - '7997:7997'
      - '8000-8002:8000-8002'
      - '8010-8011:8010-8011'
      - '8013:8013'
    hostname: 'marklogic.local'
    container_name: 'marklogic.local'
    environment:
      USER: ${ML_USER}
      PASS: ${ML_PASS}
    networks:
      - 'marklogic'
    volumes:
      - 'marklogic:/var/opt/MarkLogic'
  datahub:  
    build: 
      context: 'ml-data-hub-quick-start'
    depends_on: 
      - 'marklogic'
    image: 'ml-data-hub-quick-start:latest'
    ports:
      - '8080:8080'
    hostname: 'datahub.local'
    container_name: 'datahub.local'
    networks:
      - 'marklogic'
    # Have you use a data bind mount instead of a namved volume due to an issue mounting windows volumes.   
    volumes:
      - '../data-hub:/data-hub'
networks:
  marklogic:
    driver: 'bridge'
volumes:
  marklogic: